
t = 0
   ID  Size  User  Prio
    1    50     0    70
Now starting job 1

t = 1, current job 1 ends at t=5
   ID  Size  User  Prio
    2    10     0   110

t = 2, current job 1 ends at t=5
   ID  Size  User  Prio
    2    10     0   110
    3    20     5    95

t = 3, current job 1 ends at t=5
   ID  Size  User  Prio
    2    10     0   110
    4    10     1   109
    3    20     5    95

t = 4, current job 1 ends at t=5
   ID  Size  User  Prio
    2    10     0   110
    4    10     1   109
    3    20     5    95

t = 5, current job 1 ends at t=5
   ID  Size  User  Prio
    2    10     0   110
    4    10     1   109
    3    20     5    95
Now starting job 2

t = 6, current job 2 ends at t=6
   ID  Size  User  Prio
    4    10     1   109
    3    20     5    95
Now starting job 4

t = 7, current job 4 ends at t=7
   ID  Size  User  Prio
    3    20     5    95
Now starting job 3
