
t = 0
   ID  Size  User  Prio
    1    20     1    99
Now starting job 1

t = 1, current job 1 ends at t=2
   ID  Size  User  Prio
    2    20     5    95

t = 2, current job 1 ends at t=2
   ID  Size  User  Prio
    3    20     0   100
    2    20     5    95
Now starting job 3

t = 3, current job 3 ends at t=4
   ID  Size  User  Prio
    4    20     3    97
    2    20     5    95

t = 4, current job 3 ends at t=4
   ID  Size  User  Prio
    5    20     0   100
    4    20     3    97
    2    20     5    95
Now starting job 5

t = 5, current job 5 ends at t=6
   ID  Size  User  Prio
    4    20     3    97
    2    20     5    95
    6    20     5    95
Printer overload!
