
t = 0
   ID  Size  User  Prio
    1    60     1    59
Now starting job 1

t = 1, current job 1 ends at t=6
   ID  Size  User  Prio
    2    60     0    60

t = 2, current job 1 ends at t=6
   ID  Size  User  Prio
    3    50     2    68
    2    60     0    60

t = 3, current job 1 ends at t=6
   ID  Size  User  Prio
    4    50     1    69
    3    50     2    68
    2    60     0    60
Printer overload!
